export const bedDatabase = {
  "bed1": { title: "BED 1 • Roots & Greens", focus: "The Nutrient Engine", soilPrep: "Soil must be kept incredibly loose and free of rocks/clumps down to 12 inches to ensure carrots grow straight.", macroWatering: "High surface-moisture dependency early in the season. Keep the top crust damp.", macroFeeding: "The SubPod acts as the core engine here. Worm castings and liquid tea will continuously leach into this bed.", bedSecrets: "Harvest radishes quickly to free up root space." },
  "bed2": { title: "BED 2 • Allium & Herb", focus: "Bulb Swelling & Weed Defense", soilPrep: "Excellent drainage is required. Onions will rot in standing water.", macroWatering: "Standard deep soak. CRITICAL: Stop watering this bed entirely in late summer when the onion tops flop over.", macroFeeding: "Conservative spacing means nutrients last longer. Feed every 3-4 weeks.", bedSecrets: "Onions have incredibly shallow root systems. Keep this bed meticulously weed-free by hand-pulling." },
  "bed3": { title: "BED 3 • Brassicas", focus: "Heavy Leaf Production", soilPrep: "Mix heavily with rich compost before planting.", macroWatering: "Deep, consistent soaking.", macroFeeding: "This is your hungriest bed. Hit it strictly with High Nitrogen Fish Emulsion (2 Tbsp/gal) every 3 weeks.", bedSecrets: "Watch out for cabbage loopers. The scattered Sweet Alyssum on the soil surface will attract hoverflies to help hunt pests." },
  "bed4": { title: "BED 4 • Pea Trellis & Peppers", focus: "The Nitrogen Relay", soilPrep: "Install a sturdy vertical trellis along the back edge before planting.", macroWatering: "Consistent deep watering. When peppers set fruit, slightly stress them (water less) right before picking to increase spice.", macroFeeding: "Start with 4-4-4, switch to Fruiting Fertilizer (2-8-4) once peppers flower.", bedSecrets: "The Sugar Snap Peas are legumes—they pull nitrogen from the air. As they die off in July, they leave primed soil for your peppers." },
  "bed5": { title: "BED 5 • Vines & Beans", focus: "Vertical Jungle", soilPrep: "Requires the heaviest, tallest trellising in the garden.", macroWatering: "Thirstiest bed in July/August. Never let this bed fully dry out during peak heat.", macroFeeding: "Light feeding (5-1-1). Beans are nitrogen-fixers.", bedSecrets: "Cucumbers and beans require aggressive daily harvesting to keep producing." },
  "bed6": { title: "BED 6 • Tomatillo Hub", focus: "Controlled Chaos", soilPrep: "Install heavy-duty wire cages early.", macroWatering: "Deep root soaking. Water the base of the plants, not leaves.", macroFeeding: "Fruiting Fertilizer (2-8-4) every 2-3 weeks.", bedSecrets: "Tomatillos are strictly not self-pollinating. You must ensure both plants in this bed survive and bloom at the same time." },
  "bed7": { title: "BED 7 • Tomato & Basil Haven", focus: "Heavy Fruiting", soilPrep: "Dig deep holes for the tomatoes. Bury the stems deep.", macroWatering: "Deep root soaking. Cut water volume by 50% in late summer to force ripening.", macroFeeding: "Fruiting Fertilizer (2-8-4) every 2-3 weeks.", bedSecrets: "Once tomatoes are 3 feet tall, prune off all branches in the bottom 12 inches to prevent soil-borne fungus." }
};

export const plantDatabase = {
  "Radishes": { color: "#ff8fab", method: "DIRECT SOW (Precision Poke)", quantity: "16 seeds", depth: "1/2 inch", harvest: "25-30 days", phases: [{ name: "Sprouting", startDay: 0, waterDays: 1, water: "Daily mist to keep soil soft.", feedDays: 14, feed: "Light Fish Emulsion (5-1-1)", pruning: "Snip the weakest sprouts with scissors at the soil line.", tip: "Keep the surface wet so the roots can easily push down into the dirt." }, { name: "Bulbing", startDay: 15, waterDays: 2, water: "Standard soak.", feedDays: null, feed: "None", pruning: "Keep area weed-free.", tip: "Lightning fast. Harvest promptly right around Day 25 to free up root space." }]},
  "Carrots": { color: "#ffb703", method: "DIRECT SOW (Scatter & Thin)", quantity: "Thin to 9", depth: "1/4 inch", harvest: "70-80 days", phases: [{ name: "Germination", startDay: 0, waterDays: 1, water: "Needs daily moisture! Use cardboard trick.", feedDays: null, feed: "None required yet.", pruning: "Do not touch the soil surface.", tip: "Seeds are tiny and take forever to sprout. Keep the cardboard on until you see green." }, { name: "Maturation", startDay: 21, waterDays: 3, water: "Deep soak every 3 days.", feedDays: 21, feed: "Light Fish Emulsion (5-1-1)", pruning: "Thin down to a conservative 9 per sq ft.", tip: "When weeding, cut weeds at the base rather than pulling, so you don't disturb the carrot taproots." }, { name: "Harvest Window", startDay: 65, waterDays: 3, water: "Standard soak.", feedDays: null, feed: "None", pruning: "None.", tip: "A light frost actually forces sugars into the root. Leave them in the ground until you need to eat them." }]},
  "Buttercrunch & Romaine": { color: "#90be6d", method: "DIRECT SOW (Precision Poke)", quantity: "4 seeds", depth: "Surface", harvest: "55-65 days", phases: [{ name: "Seedling", startDay: 0, waterDays: 2, water: "Keep surface damp.", feedDays: 14, feed: "Light Fish Emulsion (5-1-1)", pruning: "Snip weakest sprouts.", tip: "Lettuce needs light to germinate. Press seeds firmly into dirt, do not bury them." }, { name: "Growth", startDay: 25, waterDays: 2, water: "Standard soak.", feedDays: 14, feed: "Fish Emulsion", pruning: "Harvest outer leaves only.", tip: "Pick the outermost leaves for salads and the center will keep growing." }]},
  "Arugula": { color: "#73a942", method: "DIRECT SOW (Scatter & Thin)", quantity: "Thin to 9", depth: "1/2 inch", harvest: "40-50 days", phases: [{ name: "Growth", startDay: 0, waterDays: 2, water: "Standard soak.", feedDays: 14, feed: "Light Fish Emulsion (5-1-1)", pruning: "Thin to 9 plants.", tip: "Flea beetles love arugula. Keep an eye out for tiny holes in the leaves." }, { name: "Harvest", startDay: 30, waterDays: 2, water: "Standard soak.", feedDays: 14, feed: "Light Fish Emulsion", pruning: "Cut leaves 1 inch above soil.", tip: "Continuous Harvest Secret: Never pull the roots. Just cut the leaves and it will regrow." }]},
  "Spinach": { color: "#538d22", method: "DIRECT SOW (Precision Poke)", quantity: "9 seeds", depth: "1/2 inch", harvest: "40-50 days", phases: [{ name: "Growth", startDay: 0, waterDays: 2, water: "Standard soak.", feedDays: 14, feed: "Light Fish Emulsion (5-1-1)", pruning: "Keep weed free.", tip: "Loves the cool spring. If the weather gets too hot, it will 'bolt' (go to seed) and turn bitter." }, { name: "Harvest", startDay: 35, waterDays: 2, water: "Standard soak.", feedDays: 14, feed: "Light Fish Emulsion", pruning: "Cut outermost leaves.", tip: "Shade with taller crops later in the season to extend its life." }]},
  "Red Onions": { color: "#cda4f4", method: "TRANSPLANT", quantity: "4 plants", depth: "Root depth", harvest: "90-110 days", phases: [{ name: "Bulb Swelling", startDay: 0, waterDays: 3, water: "Standard deep soak.", feedDays: 28, feed: "Fish Emulsion every 4 weeks.", pruning: "Hand-pull ALL weeds immediately.", tip: "Growing Secret: Onions have tiny roots and hate competition. The bed must be perfectly weed-free." }, { name: "Curing", startDay: 80, waterDays: null, water: "CRITICAL: Stop watering entirely.", feedDays: null, feed: "None.", pruning: "Do not touch them.", tip: "When the green tops flop over, they are done growing. Let them sit in dry dirt for a week to cure the skins." }]},
  "Yellow Onions": { color: "#fcefb4", method: "TRANSPLANT", quantity: "4 plants", depth: "Root depth", harvest: "90-110 days", phases: [{ name: "Bulb Swelling", startDay: 0, waterDays: 3, water: "Standard deep soak.", feedDays: 28, feed: "Fish Emulsion every 4 weeks.", pruning: "Hand-pull ALL weeds immediately.", tip: "Growing Secret: Onions have tiny roots and hate competition. The bed must be perfectly weed-free." }, { name: "Curing", startDay: 80, waterDays: null, water: "CRITICAL: Stop watering entirely.", feedDays: null, feed: "None.", pruning: "Do not touch them.", tip: "When the green tops flop over, they are done growing. Let them sit in dry dirt for a week to cure the skins." }]},
  "Parsley": { color: "#a7c957", method: "DIRECT SOW (Precision Poke)", quantity: "2 seeds", depth: "1/4 inch", harvest: "60-70 days", phases: [{ name: "Seedling", startDay: 0, waterDays: 2, water: "Daily mist until sprout.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Snip weakest sprout.", tip: "Extremely slow to germinate. Don't give up on it." }, { name: "Growth", startDay: 30, waterDays: 2, water: "Standard soak.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Snip stems from outside in.", tip: "Always harvest from the outer edge so the center crown continues pushing new growth." }]},
  "Cilantro": { color: "#a7c957", method: "DIRECT SOW (Precision Poke)", quantity: "2 seeds", depth: "1/4 inch", harvest: "60-70 days", phases: [{ name: "Seedling", startDay: 0, waterDays: 2, water: "Daily mist until sprout.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Snip weakest sprout.", tip: "Crack the round seed shell gently before planting to speed up germination." }, { name: "Growth", startDay: 25, waterDays: 2, water: "Standard soak.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Harvest aggressively.", tip: "Bolts instantly in high heat. Cut it often to delay flowering." }]},
  "Broccoli": { color: "#4c956c", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "50-70 days", phases: [{ name: "Heavy Growth", startDay: 0, waterDays: 3, water: "Deep soak 2-3x a week.", feedDays: 21, feed: "High Nitrogen (2 Tbsp/gal)", pruning: "Check under leaves for eggs.", tip: "Very heavy feeder. Watch out for little white moths—they lay the green cabbage looper caterpillars." }, { name: "Fruiting", startDay: 45, waterDays: 3, water: "Deep soak.", feedDays: 21, feed: "High Nitrogen", pruning: "Cut main head before it flowers.", tip: "Harvest the big head while it's tight. If you see yellow flowers, you waited too long." }, { name: "Side-Shoots", startDay: 60, waterDays: 3, water: "Deep soak.", feedDays: 21, feed: "High Nitrogen", pruning: "Harvest mini-florets.", tip: "After cutting the main head, leave the plant! It will push out smaller side-shoots for weeks." }]},
  "Dwarf Siberian Kale": { color: "#2c6e49", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "50-70 days", phases: [{ name: "Growth", startDay: 0, waterDays: 3, water: "Standard soak.", feedDays: 21, feed: "High Nitrogen Fish Emulsion", pruning: "Harvest outermost leaves.", tip: "Twist leaves off downwards to snap them cleanly from the main stalk." }, { name: "Late Season", startDay: 60, waterDays: 3, water: "Standard soak.", feedDays: 21, feed: "High Nitrogen Fish Emulsion", pruning: "Keep harvesting.", tip: "A light frost causes the plant to push sugars into the leaves, making them significantly sweeter." }]},
  "Collard Greens": { color: "#6a994e", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "50-70 days", phases: [{ name: "Growth", startDay: 0, waterDays: 3, water: "Standard soak.", feedDays: 21, feed: "High Nitrogen Fish Emulsion", pruning: "Harvest outermost leaves.", tip: "Just like kale, harvest from the bottom up. The plant will eventually look like a small palm tree." }]},
  "Sugar Snap Peas": { color: "#d9ed92", method: "DIRECT SOW (Precision Poke)", quantity: "9 seeds", depth: "1 inch", harvest: "60-70 days", phases: [{ name: "Climbing", startDay: 0, waterDays: 2, water: "Standard soak.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Guide tendrils to trellis.", tip: "Peas hate hot weather. Get them climbing the trellis early so they get good airflow." }, { name: "Fruiting", startDay: 45, waterDays: 2, water: "Standard soak.", feedDays: null, feed: "None (Nitrogen Fixer)", pruning: "Harvest every 1-2 days.", tip: "The more you pick, the more flowers it pushes. Never let a pod get overly fat and bumpy." }]},
  "Green Beans": { color: "#b5e48c", method: "DIRECT SOW (Precision Poke)", quantity: "9 seeds", depth: "1 inch", harvest: "50-60 days", phases: [{ name: "Climbing", startDay: 0, waterDays: 2, water: "Standard soak.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Guide to trellis.", tip: "Beans are nitrogen fixers. They pull their own food from the air, so don't over-fertilize them." }, { name: "Fruiting", startDay: 40, waterDays: 2, water: "Standard soak.", feedDays: null, feed: "None", pruning: "Harvest every 1-2 days.", tip: "Pick them when they are slender. If you can see the beans bulging inside the pod, they will be tough." }]},
  "Cucumbers": { color: "#52b788", method: "DIRECT SOW (Precision Poke)", quantity: "2 seeds (thin to 1)", depth: "1 inch", harvest: "50-70 days", phases: [{ name: "Vining", startDay: 0, waterDays: 2, water: "Heavy drinker. Deep soak.", feedDays: 14, feed: "Light Fish Emulsion", pruning: "Snip weakest seedling.", tip: "Poke 2 seeds per hole, snip the weakest one. Train the surviving vine up the trellis immediately." }, { name: "Fruiting", startDay: 45, waterDays: 2, water: "Heavy deep soak.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4)", pruning: "Pick continuously.", tip: "Water is critical now. A thirsty cucumber plant will produce bitter, twisted fruit." }]},
  "Roma Tomato": { color: "#e63946", method: "TRANSPLANT (Deep Trench)", quantity: "1 massive plant", depth: "Bury stem deep", harvest: "65-85 days", phases: [{ name: "Vegetative", startDay: 0, waterDays: 3, water: "Deep root soak. Keep leaves dry.", feedDays: 14, feed: "Start with 4-4-4.", pruning: "Pinch off early armpit suckers.", tip: "Transplanting Secret: Strip the bottom leaves and bury the stem horizontally. The buried stem will grow a massive taproot." }, { name: "Heavy Growth", startDay: 30, waterDays: 3, water: "Deep root soak.", feedDays: 14, feed: "Switch to 2-8-4.", pruning: "Aggressive pruning. Clear bottom 12 inches.", tip: "Remove all branches touching the ground. Soil splashing onto leaves is how blight starts." }, { name: "Ripening", startDay: 60, waterDays: 5, water: "Cut water volume by 50%.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4)", pruning: "Maintain airflow.", tip: "Fruiting Secret: Drought stress forces the plant to panic and dump all its sugars into ripening the fruit. Less water = better flavor." }]},
  "Beefsteak": { color: "#d62828", method: "TRANSPLANT (Deep Trench)", quantity: "1 massive plant", depth: "Bury stem deep", harvest: "80-90 days", phases: [{ name: "Vegetative", startDay: 0, waterDays: 3, water: "Deep root soak.", feedDays: 14, feed: "Start with 4-4-4.", pruning: "Pinch suckers.", tip: "Bury the stem deep. You are building the root engine right now." }, { name: "Heavy Growth", startDay: 35, waterDays: 3, water: "Deep root soak.", feedDays: 14, feed: "Switch to 2-8-4.", pruning: "Clear bottom 12 inches.", tip: "These are heavy tomatoes. Make sure your trellis or cage is fully secured." }, { name: "Ripening", startDay: 70, waterDays: 5, water: "Cut water volume by 50%.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4)", pruning: "Maintain airflow.", tip: "Drought stress forces ripening. Pick them right as they 'blush' red and let them finish ripening on the kitchen counter to prevent bug damage." }]},
  "Cherry Tomato": { color: "#f25c54", method: "TRANSPLANT (Deep Trench)", quantity: "1 massive plant", depth: "Bury stem deep", harvest: "65-75 days", phases: [{ name: "Vegetative", startDay: 0, waterDays: 3, water: "Deep root soak.", feedDays: 14, feed: "Start with 4-4-4.", pruning: "Pinch early suckers only.", tip: "Bury stem deep. Establish the roots." }, { name: "Wild Fruiting", startDay: 40, waterDays: 4, water: "Consistent deep soak.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4).", pruning: "Let it vine out wildly.", tip: "Fruiting Secret: Cherry tomatoes are chaotic. Unlike Romas, you don't need to strictly prune suckers. Let them become a massive bush over the trellis." }]},
  "Tomatillo": { color: "#a7c957", method: "TRANSPLANT", quantity: "1 massive plant", depth: "Bury stem deep", harvest: "65-85 days", phases: [{ name: "Growth & Bloom", startDay: 0, waterDays: 3, water: "Deep soak base, not leaves.", feedDays: 21, feed: "Fruiting Fertilizer (2-8-4)", pruning: "Cage immediately.", tip: "Strictly not self-pollinating. If one plant dies, the other will drop empty husks. Protect them both." }, { name: "Fruiting", startDay: 50, waterDays: 3, water: "Deep soak.", feedDays: 21, feed: "Fruiting Fertilizer (2-8-4)", pruning: "Support heavy branches.", tip: "Harvest when the green fruit completely fills the papery husk and the husk splits open at the bottom." }]},
  "Basil": { color: "#74c69d", method: "TRANSPLANT", quantity: "4 plants", depth: "Crown level", harvest: "30-40 days", phases: [{ name: "Growth", startDay: 0, waterDays: 2, water: "Standard soak.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Pinch top clusters.", tip: "Never let it flower. Pinch the top leaves off so it bushes outwards into a massive shrub." }]},
  "Thai Basil": { color: "#52b788", method: "TRANSPLANT", quantity: "4 plants", depth: "Crown level", harvest: "30-40 days", phases: [{ name: "Growth", startDay: 0, waterDays: 2, water: "Standard soak.", feedDays: 21, feed: "Light Fish Emulsion", pruning: "Pinch top clusters.", tip: "Great companion for tomatoes, the heavy scent masks the smell of the tomatoes from pests." }]},
  "Bell Pepper": { color: "#f4a261", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "70-80 days", phases: [{ name: "Frame Building", startDay: 0, waterDays: 3, water: "Consistent deep watering.", feedDays: 21, feed: "Start with 4-4-4.", pruning: "Pluck the very first blossoms.", tip: "Growing Secret: Pluck the first round of flowers off so the plant builds a stronger physical frame first." }, { name: "Fruiting", startDay: 45, waterDays: 4, water: "Slight stress before picking.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4).", pruning: "Provide stake support.", tip: "You can eat them green, but if you leave them on the plant for another 2-3 weeks they will turn red and sweeten dramatically." }]},
  "Jalapeno": { color: "#2a9d8f", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "70-80 days", phases: [{ name: "Frame Building", startDay: 0, waterDays: 3, water: "Consistent deep watering.", feedDays: 21, feed: "Start with 4-4-4.", pruning: "Pluck first blossoms.", tip: "Pinch early flowers to build a strong canopy." }, { name: "Spice Forcing", startDay: 45, waterDays: 5, water: "Drought stress before harvest.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4).", pruning: "Snip with shears.", tip: "Fruiting Secret: Heat & drought stress right before harvest spikes the capsaicin. Look for brown 'corking' lines on the skin for max spice." }]},
  "Serrano": { color: "#2a9d8f", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "70-80 days", phases: [{ name: "Frame Building", startDay: 0, waterDays: 3, water: "Consistent deep watering.", feedDays: 21, feed: "Start with 4-4-4.", pruning: "Pluck first blossoms.", tip: "Pinch early flowers to build a strong canopy." }, { name: "Spice Forcing", startDay: 45, waterDays: 5, water: "Drought stress before harvest.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4).", pruning: "Snip with shears.", tip: "Smaller and significantly spicier than Jalapenos. Drought stress increases the heat." }]},
  "Thai Hot": { color: "#e63946", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "70-80 days", phases: [{ name: "Frame Building", startDay: 0, waterDays: 3, water: "Consistent deep watering.", feedDays: 21, feed: "Start with 4-4-4.", pruning: "Pluck first blossoms.", tip: "Pinch early flowers to build a strong canopy." }, { name: "Spice Forcing", startDay: 45, waterDays: 5, water: "Drought stress before harvest.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4).", pruning: "Snip with shears.", tip: "Produces hundreds of tiny peppers facing straight up at the sky. They turn bright red when fully spicy." }]},
  "Shishito": { color: "#a7c957", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "60-70 days", phases: [{ name: "Growth", startDay: 0, waterDays: 3, water: "Consistent deep watering.", feedDays: 21, feed: "Start with 4-4-4.", pruning: "Pluck first blossoms.", tip: "Build the frame before letting it fruit." }, { name: "Harvesting", startDay: 40, waterDays: 3, water: "Standard soak.", feedDays: 14, feed: "Fruiting Fertilizer (2-8-4).", pruning: "Harvest continuously.", tip: "Harvest when they are 2-3 inches long, green, and very wrinkled. Roughly 1 in 10 will be spicy." }]},
  "Marigold": { color: "#fb8500", method: "TRANSPLANT", quantity: "1 plant", depth: "Crown level", harvest: "50 days", phases: [{ name: "Bloom", startDay: 0, waterDays: 3, water: "Standard soak.", feedDays: null, feed: "None required.", pruning: "Deadhead dead flowers.", tip: "The roots secrete a chemical that actively kills root-knot nematodes in the soil." }]},
  "Nasturtiums": { color: "#ff5400", method: "DIRECT SOW (Precision Poke)", quantity: "2 seeds", depth: "1 inch", harvest: "55-65 days", phases: [{ name: "Bloom", startDay: 0, waterDays: 3, water: "Standard soak.", feedDays: null, feed: "None required.", pruning: "Cascade over the bed edge.", tip: "A sacrificial trap crop. Aphids will attack this instead of your vegetables." }]},
  "Calendula": { color: "#ffb703", method: "DIRECT SOW (Precision Poke)", quantity: "1 seed", depth: "1/4 inch", harvest: "50-60 days", phases: [{ name: "Bloom", startDay: 0, waterDays: 3, water: "Standard soak.", feedDays: null, feed: "None required.", pruning: "Deadhead spent blooms.", tip: "Attracts predatory insects that hunt garden pests." }]},
  "SubPod": { color: "#ebd9c8", method: "INFRASTRUCTURE", quantity: "-", depth: "-", harvest: "Continuous", phases: [{ name: "Active", startDay: 0, waterDays: null, water: "Keep moist.", feedDays: null, feed: "Kitchen scraps", pruning: "-", tip: "The nutrient engine. Add brown cardboard with food scraps to balance carbon." }] },
  "Open Space": { color: "#e9ecef", method: "-", quantity: "0", depth: "-", harvest: "-", phases: [{ name: "Empty", startDay: 0, waterDays: null, water: "-", feedDays: null, feed: "-", pruning: "-", tip: "Reserved area." }] }
};

export const masterCatalog = {
  "🌱 Seed Packets": ["Radish Seeds", "Carrot Seeds", "Beet Seeds", "Lettuce Seeds", "Arugula Seeds", "Spinach Seeds", "Swiss Chard Seeds", "Pea Seeds", "Green Bean Seeds", "Cucumber Seeds", "Zucchini Seeds", "Butternut Squash Seeds", "Pumpkin Seeds", "Sweet Corn Seeds", "Red Onion Seeds", "Yellow Onion Seeds", "Broccoli Seeds", "Cabbage Seeds", "Kale Seeds", "Collard Greens Seeds", "Roma Tomato Seeds", "Beefsteak Tomato Seeds", "Cherry Tomato Seeds", "Tomatillo Seeds", "Eggplant Seeds", "Bell Pepper Seeds", "Jalapeno Seeds", "Serrano Seeds", "Thai Hot Seeds", "Shishito Seeds", "Basil Seeds", "Thai Basil Seeds", "Cilantro Seeds", "Parsley Seeds", "Marigold Seeds", "Nasturtium Seeds", "Calendula Seeds", "Sunflower Seeds"],
  "🪴 Transplants": ["Lettuce Starts", "Arugula Starts", "Spinach Starts", "Swiss Chard Starts", "Pea Starts", "Green Bean Starts", "Cucumber Starts", "Zucchini Starts", "Butternut Squash Starts", "Pumpkin Starts", "Sweet Corn Starts", "Red Onion Starts", "Yellow Onion Starts", "Broccoli Starts", "Cabbage Starts", "Kale Starts", "Collard Greens Starts", "Roma Tomato Starts", "Beefsteak Starts", "Cherry Tomato Starts", "Tomatillo Starts", "Eggplant Starts", "Bell Pepper Starts", "Jalapeno Starts", "Serrano Starts", "Thai Hot Starts", "Shishito Starts", "Basil Starts", "Thai Basil Starts", "Cilantro Starts", "Parsley Starts", "Marigold Starts", "Nasturtium Starts", "Calendula Starts", "Sunflower Starts"],
  "🪨 Soils & Amendments": ["Organic Compost (Bag)", "Potting Soil (Bag)", "Coco Coir (Brick)", "Vermiculite (Bag)", "Perlite (Bag)", "Fish Emulsion (5-1-1)", "Fruiting Fertilizer (2-8-4)", "Bone Meal", "Blood Meal", "Kelp Meal", "Mycorrhizal Fungi", "Worm Blanket", "SubPod Carbon Bedding", "Straw Mulch"],
  "🛠️ Hardware": ["Drip Tubing (1/2\")", "Drip Tubing (1/4\")", "Drip Emitters", "Irrigation Stakes", "Hose Timer", "Tomato Cages", "Trellis Netting", "Korean EZ Digger", "Pruning Snips", "Twine", "Seedling Trays", "Heat Mat", "Grow Lights", "Plant Tags", "Neem Oil", "Slug/Snail Bait", "Frost Cover"]
};